//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProperty
    {
        public int ID { get; set; }
        public int CategoryLID { get; set; }
        public int PropertyID { get; set; }
        public bool IsFind { get; set; }
        public bool IsBasic { get; set; }
        public bool IsFull { get; set; }
    
        public virtual CategoryL CategoryL { get; set; }
        public virtual Property Property { get; set; }
    }
}
