//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCategory
    {
        public FCategory()
        {
            this.FCategories1 = new HashSet<FCategory>();
            this.FCategoryLs = new HashSet<FCategoryL>();
        }
    
        public int ID { get; set; }
        public Nullable<byte> Priority { get; set; }
        public bool IsLock { get; set; }
        public Nullable<int> FCategoryID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<FCategory> FCategories1 { get; set; }
        public virtual FCategory FCategory1 { get; set; }
        public virtual ICollection<FCategoryL> FCategoryLs { get; set; }
    }
}
