//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Pictures = new HashSet<Picture>();
            this.PriceCharts = new HashSet<PriceChart>();
            this.ProductDetails = new HashSet<ProductDetail>();
            this.ProductLs = new HashSet<ProductL>();
        }
    
        public int ID { get; set; }
        public string Photo { get; set; }
        public bool IsNew { get; set; }
        public int Status { get; set; }
        public decimal Price { get; set; }
        public decimal PriceSell { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public bool IsLock { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<PriceChart> PriceCharts { get; set; }
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual ICollection<ProductL> ProductLs { get; set; }
    }
}
