//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public Slider()
        {
            this.SliderLs = new HashSet<SliderL>();
        }
    
        public int ID { get; set; }
        public string Photo { get; set; }
        public Nullable<byte> Priority { get; set; }
        public bool IsLock { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<SliderL> SliderLs { get; set; }
    }
}
